name: budget_zen
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.6
  google_sign_in: ^6.3.0
  firebase_dynamic_links: ^6.1.5
  cloud_firestore: ^5.6.8
  shared_preferences: ^2.5.3
  intl: ^0.18.1  # ou la version la plus récente
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  month_picker: ^0.0.4
  month_picker_dialog: ^2.12.0
  flutter_charts: ^0.5.2
  rxdart: ^0.28.0
  google_api_availability: ^5.0.1
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  
  android_12:
    image: assets/icon.png
    image_dark: assets/icon.png
    # Ne pas définir de icon_background_color => pas de fond sous l'icône

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.png
    - assets/logoWithProjectName.png
    - assets/logoSimple.png
    - assets/noStatisticsImage.png
    - assets/noTransactionImage.png
    - assets/orange_money_logo.png